"""Public immutable contracts for stateful scientific research projects."""

from .artifact_store import ArtifactPayload, ProjectArtifactStore
from .artifacts import QUALITY_STATUSES, ScientificArtifact
from .context import CONSTRAINT_KINDS, PRIVACY_LEVELS, Comparison, Constraint, ProjectContext
from .evidence import EVIDENCE_RELATIONS, EvidenceRecord, add_evidence, evidence_partition, independent_evidence_groups
from .hypotheses import CLAIM_STRENGTHS, EXPECTED_DIRECTIONS, HYPOTHESIS_STATUSES, Hypothesis, add_hypothesis, attach_evidence, revise_hypothesis
from .decisions import DecisionEvent
from .plans import NODE_STATUSES, PLAN_TYPES, PlanNode, ResearchDAG, RevisionTargetContract
from .state import (
    EVENT_TYPES,
    LegacyEvidenceMapRecord,
    ProjectState,
    StateMigrationContractUpgrade,
    StateMigrationRecord,
    apply_event,
    replay,
)
from .identity import FrozenMapping, canonical_json, digest_value, freeze_mapping, redact_sensitive, thaw, validate_identifier
from .scientific_dependency import (
    ARTIFACT_KINDS,
    DECISION_ACTIONS,
    REVIEW_STATUSES,
    AnalysisAdmission,
    ArtifactReview,
    LegacyAnalysisAdmissionRecovery,
    PanelInterpretation,
    ScientificDecision,
    ScientificDependencyBundle,
    ScientificDependencyGraph,
    build_scientific_dependency_graph,
)
from .scientific_evidence_map import (
    CHANGE_TYPES,
    FILE_ROLES,
    SOURCE_ROLES,
    EvidenceFile,
    EvidenceMapEdge,
    EvidenceMapUnit,
    EvidenceMapVersion,
    EvidenceUnitSpec,
    NarrativeSource,
    ScientificEvidenceMap,
    build_scientific_evidence_map,
    validate_evidence_map_files,
)

__all__ = [
    "CONSTRAINT_KINDS",
    "CLAIM_STRENGTHS",
    "EVIDENCE_RELATIONS",
    "EVENT_TYPES",
    "EXPECTED_DIRECTIONS",
    "HYPOTHESIS_STATUSES",
    "NODE_STATUSES",
    "PLAN_TYPES",
    "PRIVACY_LEVELS",
    "QUALITY_STATUSES",
    "Comparison",
    "Constraint",
    "DecisionEvent",
    "EvidenceRecord",
    "FrozenMapping",
    "ArtifactPayload",
    "ARTIFACT_KINDS",
    "DECISION_ACTIONS",
    "REVIEW_STATUSES",
    "AnalysisAdmission",
    "ArtifactReview",
    "LegacyAnalysisAdmissionRecovery",
    "PanelInterpretation",
    "ScientificDecision",
    "ScientificDependencyBundle",
    "ScientificDependencyGraph",
    "CHANGE_TYPES",
    "FILE_ROLES",
    "SOURCE_ROLES",
    "EvidenceFile",
    "EvidenceMapEdge",
    "EvidenceMapUnit",
    "EvidenceMapVersion",
    "EvidenceUnitSpec",
    "NarrativeSource",
    "ScientificEvidenceMap",
    "ProjectArtifactStore",
    "ProjectContext",
    "Hypothesis",
    "PlanNode",
    "RevisionTargetContract",
    "ProjectState",
    "LegacyEvidenceMapRecord",
    "StateMigrationContractUpgrade",
    "StateMigrationRecord",
    "ResearchDAG",
    "ScientificArtifact",
    "canonical_json",
    "add_evidence",
    "add_hypothesis",
    "apply_event",
    "attach_evidence",
    "build_scientific_dependency_graph",
    "build_scientific_evidence_map",
    "validate_evidence_map_files",
    "digest_value",
    "freeze_mapping",
    "evidence_partition",
    "independent_evidence_groups",
    "redact_sensitive",
    "replay",
    "revise_hypothesis",
    "thaw",
    "validate_identifier",
]
