"""One-time scientific enrichment used to migrate the v0.2 capability catalog."""

from __future__ import annotations


QUESTIONS = {
    "adverse-event-summary": "What adverse events occurred, in how many participants, at what grades and seriousness?",
    "biomarker-performance": "How well does a continuous biomarker discriminate a prespecified binary outcome at the declared threshold?",
    "citation-audit": "Which references are incomplete, malformed, or duplicated before external verification?",
    "clinical-deidentify": "Which direct identifiers and common contact patterns can be removed from a structured research record?",
    "clinical-report-audit": "Which required reporting sections are present or absent for the selected clinical reporting standard?",
    "cohort-summary": "What are the sample denominator, missingness, distributions, and category frequencies of a research cohort?",
    "crispr-design": "Which sequence contexts satisfy the declared SpCas9 guide and PAM rules for downstream validation?",
    "data-profile": "What are the shape, types, missingness, uniqueness, and numeric ranges of a scientific table?",
    "differential-expression": "Which features differ between two declared groups under a compact Welch-test analysis?",
    "dilution-plan": "What concentrations and transfer volumes produce the requested serial dilution series?",
    "dose-response": "Is the observed response monotonic and where does it cross the empirical half range?",
    "enrichment-analysis": "Which declared gene sets are overrepresented relative to the explicit background universe?",
    "enzyme-kinetics": "Which steady-state kinetic parameters and model diagnostics best describe the supplied observations?",
    "expression-qc": "Do expression libraries have adequate size, detection, sparsity, and consistency for downstream analysis?",
    "figure-specification": "Does every figure panel state a unique claim, data source, and plot form?",
    "flow-cytometry-summary": "How many events pass each sequential parent gate and what fraction of parent and total do they represent?",
    "gene-evidence": "Which NCBI gene record and linked protein, ClinVar, and literature records ground the requested gene?",
    "glycosylation-scan": "Which protein positions contain N-linked sequons or serine/threonine-rich contexts and what can they support?",
    "golden-gate-plan": "Is the ordered Type IIS assembly free of internal sites, incompatible junctions, and risky overhang reuse?",
    "growth-curve": "What maximum log-phase growth rate and doubling time are supported by the measured series?",
    "image-colocalization": "How strongly do two aligned image channels correlate and overlap above declared thresholds?",
    "image-profile": "What are the intensity distribution, sparsity, and shape of a numeric scientific image?",
    "image-segment": "Which connected components result from the declared threshold, polarity, and connectivity?",
    "immunoassay-quantification": "Does the calibration fit support back-calculation of unknown concentrations within the validated response range?",
    "literature-evidence": "Which PubMed or PMC records match the bounded query and what query translation was applied?",
    "manuscript-audit": "Are manuscript structure, claim grounding, figures, data, and code availability ready for expert review?",
    "ncbi-fetch": "What bounded full records are returned for the declared Entrez database and identifiers?",
    "ncbi-info": "What databases, fields, links, and update metadata does Entrez report for the requested scope?",
    "ncbi-link": "Which records in a target Entrez database are linked to the supplied source identifiers?",
    "ncbi-search": "Which Entrez identifiers match the bounded database query?",
    "ncbi-search-summary": "Which Entrez records result from a search followed by bounded summary retrieval?",
    "ncbi-summary": "What normalized document summaries correspond to the supplied Entrez identifiers?",
    "network-analysis": "What nodes, edges, components, degrees, and hubs describe the supplied biological network?",
    "patent-disclosure-audit": "Does a research disclosure identify the inventive problem, solution, essential features, enablement, alternatives, and prior art?",
    "pcr-plan": "What per-reaction and overage-adjusted master-mix volumes conserve the declared PCR volume?",
    "point-tracking": "Which detections can be linked into bounded nearest-neighbor trajectories across frames?",
    "primer-design": "Which facing primer pairs best satisfy declared length and Primer3 thermodynamic constraints before reference-aware specificity review?",
    "qpcr-relative-expression": "What efficiency-corrected relative expression is supported after replicate and multi-reference normalization?",
    "response-matrix": "Has every reviewer comment been linked to a response, manuscript action, and resolution status?",
    "restriction-plan": "Where do the selected restriction motifs occur in the supplied DNA sequence?",
    "reviewer-assessment": "Which manuscript claims and review domains create major or minor concerns under the supplied evidence design?",
    "sequence-back-translate": "What deterministic preferred-codon DNA sequence encodes the supplied protein for the selected organism?",
    "sequence-inspect": "What composition, ambiguity, GC content, and strand representation characterize the supplied sequence?",
    "single-cell-qc": "Which cells fail declared count, feature, or mitochondrial-fraction quality thresholds?",
    "survival-analysis": "What product-limit survival curve and median are supported by the supplied durations and censoring indicators?",
    "tumor-mutation-burden": "What mutation burden results after explicit somatic, filter, effect, allele-fraction, and callable-territory rules?",
    "variant-evidence": "Which ClinVar records and linked gene and literature records ground the requested variant query?",
    "variant-summary": "What variant types, filters, chromosomes, and transition-transversion balance characterize the supplied variants?",
}


CHINESE_INTENTS = {
    "adverse-event-summary": "汇总不良事件、严重性与受试者发生率",
    "biomarker-performance": "评估生物标志物诊断性能",
    "citation-audit": "审计参考文献完整性与重复 DOI",
    "clinical-deidentify": "临床研究记录去标识化",
    "clinical-report-audit": "检查临床报告规范完整性",
    "cohort-summary": "汇总临床队列基线特征",
    "crispr-design": "设计 CRISPR sgRNA 候选",
    "data-profile": "检查科研数据表结构和缺失值",
    "differential-expression": "进行差异表达分析",
    "dilution-plan": "设计连续稀释方案",
    "dose-response": "分析剂量反应关系",
    "enrichment-analysis": "进行基因集富集分析",
    "enzyme-kinetics": "拟合酶动力学模型",
    "expression-qc": "检查表达矩阵质量",
    "figure-specification": "设计并审计科学图表面板",
    "flow-cytometry-summary": "汇总流式细胞术门控结果",
    "gene-evidence": "整合基因、蛋白、变异和文献证据",
    "glycosylation-scan": "扫描蛋白糖基化序列环境",
    "golden-gate-plan": "检查 Golden Gate 克隆组装",
    "growth-curve": "分析生长曲线和倍增时间",
    "image-colocalization": "计算双通道图像共定位",
    "image-profile": "分析科研图像强度分布",
    "image-segment": "分割图像并量化连通区域",
    "immunoassay-quantification": "拟合免疫测定标准曲线并定量未知样本",
    "literature-evidence": "检索 PubMed 或 PMC 文献证据",
    "manuscript-audit": "审计论文结构、主张和可重复性",
    "ncbi-fetch": "从 NCBI Entrez 获取完整记录",
    "ncbi-info": "查询 NCBI Entrez 数据库信息",
    "ncbi-link": "查询 NCBI 数据库交叉链接",
    "ncbi-search": "搜索 NCBI Entrez 数据库",
    "ncbi-search-summary": "搜索并汇总 NCBI 记录",
    "ncbi-summary": "获取 NCBI 记录摘要",
    "network-analysis": "分析生物网络、组分和枢纽",
    "patent-disclosure-audit": "审计科研发明披露和专利准备度",
    "pcr-plan": "计算 PCR 反应和主混合液",
    "point-tracking": "追踪时间序列图像中的点目标",
    "primer-design": "设计 PCR 引物候选",
    "qpcr-relative-expression": "计算 qPCR 相对表达",
    "response-matrix": "建立审稿意见回复矩阵",
    "restriction-plan": "定位限制性内切酶位点",
    "reviewer-assessment": "进行主张证据关联的同行评审",
    "sequence-back-translate": "将蛋白序列反向翻译为编码 DNA",
    "sequence-inspect": "检查 DNA、RNA 或蛋白序列",
    "single-cell-qc": "评估单细胞表达数据质量",
    "survival-analysis": "进行 Kaplan-Meier 生存分析",
    "tumor-mutation-burden": "计算肿瘤突变负荷",
    "variant-evidence": "整合 ClinVar 变异、基因和文献证据",
    "variant-summary": "汇总变异类型、过滤和 Ti/Tv",
}


INTENT_ALIASES = {
    "adverse-event-summary": ["不良事件", "临床安全性"],
    "crispr-design": ["CRISPR设计", "sgRNA设计"],
    "differential-expression": ["差异表达"],
    "enrichment-analysis": ["基因集富集", "通路富集"],
    "flow-cytometry-summary": ["流式门控"],
    "gene-evidence": ["基因证据", "靶点证据"],
    "golden-gate-plan": ["Golden Gate组装", "克隆组装"],
    "image-segment": ["图像分割"],
    "literature-evidence": ["文献证据", "检索文献"],
    "manuscript-audit": ["写论文", "审计论文", "Nature论文"],
    "qpcr-relative-expression": ["qPCR相对表达"],
    "reviewer-assessment": ["同行评审", "Nature审稿人评审"],
    "single-cell-qc": ["单细胞质量控制", "单细胞分析"],
    "survival-analysis": ["生存分析"],
    "tumor-mutation-burden": ["肿瘤突变负荷", "TMB"],
    "variant-evidence": ["变异证据", "ClinVar证据"],
}


ARTIFACTS = {
    "adverse-event-summary": ("events", "adverse_event_table", "safety", "safety_summary"),
    "biomarker-performance": ("observations", "biomarker_table", "performance", "diagnostic_performance"),
    "citation-audit": ("references", "reference_list", "citation_quality", "quality_report"),
    "clinical-deidentify": ("record", "clinical_record", "deidentified_record", "clinical_record"),
    "clinical-report-audit": ("report", "clinical_report", "report_quality", "quality_report"),
    "cohort-summary": ("cohort", "clinical_cohort", "cohort_statistics", "statistical_summary"),
    "crispr-design": ("target_sequence", "sequence_set", "guides", "candidate_design"),
    "data-profile": ("records", "scientific_table", "profile", "quality_report"),
    "differential-expression": ("expression", "expression_matrix", "contrasts", "contrast_result"),
    "dilution-plan": ("dilution_request", "assay_plan", "dilution_series", "protocol"),
    "dose-response": ("dose_series", "assay_table", "response_summary", "statistical_summary"),
    "enrichment-analysis": ("gene_sets", "gene_set_collection", "enrichment", "enrichment_result"),
    "enzyme-kinetics": ("kinetic_observations", "assay_table", "kinetic_model", "model_fit"),
    "expression-qc": ("expression", "expression_matrix", "expression_quality", "quality_report"),
    "figure-specification": ("panel_requests", "claim_set", "figure", "figure_specification"),
    "flow-cytometry-summary": ("events", "cytometry_event_table", "gating_summary", "statistical_summary"),
    "gene-evidence": ("gene_query", "database_query", "gene_evidence", "evidence_table"),
    "glycosylation-scan": ("protein", "sequence_set", "glycosylation_contexts", "sequence_annotation"),
    "golden-gate-plan": ("fragments", "sequence_set", "assembly_plan", "candidate_design"),
    "growth-curve": ("growth_series", "assay_table", "growth_summary", "statistical_summary"),
    "image-colocalization": ("channels", "image_collection", "colocalization", "image_measurements"),
    "image-profile": ("image", "image_collection", "image_statistics", "image_measurements"),
    "image-segment": ("image", "image_collection", "segmentation", "image_segmentation"),
    "immunoassay-quantification": ("assay", "assay_table", "quantification", "calibration_result"),
    "literature-evidence": ("literature_query", "database_query", "literature_records", "literature_corpus"),
    "manuscript-audit": ("manuscript", "manuscript", "manuscript_quality", "quality_report"),
    "ncbi-fetch": ("record_request", "database_query", "records", "database_record_set"),
    "ncbi-info": ("database_request", "database_query", "database_metadata", "database_record_set"),
    "ncbi-link": ("link_request", "identifier_map", "linked_records", "identifier_map"),
    "ncbi-search": ("search_request", "database_query", "search_result", "database_record_set"),
    "ncbi-search-summary": ("search_request", "database_query", "summaries", "database_record_set"),
    "ncbi-summary": ("identifier_request", "identifier_map", "summaries", "database_record_set"),
    "network-analysis": ("network", "network", "network_summary", "network"),
    "patent-disclosure-audit": ("disclosure", "patent_disclosure", "disclosure_quality", "quality_report"),
    "pcr-plan": ("reaction_request", "assay_plan", "pcr_protocol", "protocol"),
    "point-tracking": ("detections", "image_measurements", "tracks", "trajectory"),
    "primer-design": ("template", "sequence_set", "primers", "candidate_design"),
    "qpcr-relative-expression": ("ct_measurements", "assay_table", "relative_expression", "statistical_summary"),
    "response-matrix": ("review_comments", "reviewer_report", "revision_ledger", "revision_ledger"),
    "restriction-plan": ("sequence", "sequence_set", "restriction_sites", "sequence_annotation"),
    "reviewer-assessment": ("manuscript_facts", "claim_set", "review", "reviewer_report"),
    "sequence-back-translate": ("protein", "sequence_set", "coding_sequence", "sequence_set"),
    "sequence-inspect": ("sequence", "sequence_set", "sequence_profile", "sequence_annotation"),
    "single-cell-qc": ("single_cell_counts", "count_matrix", "cell_quality", "quality_report"),
    "survival-analysis": ("survival_data", "clinical_cohort", "survival_curve", "statistical_summary"),
    "tumor-mutation-burden": ("variants", "variant_table", "mutation_burden", "statistical_summary"),
    "variant-evidence": ("variant_query", "database_query", "variant_evidence", "evidence_table"),
    "variant-summary": ("variants", "variant_table", "variant_statistics", "statistical_summary"),
}


ASSUMPTIONS = {
    "adverse-event-summary": "Participant identifiers are stable and severity grade, seriousness, and relatedness are distinct recorded attributes.",
    "biomarker-performance": "Labels represent the prespecified binary outcome and scores are evaluated without data-leaked threshold selection.",
    "citation-audit": "Reference fields supplied to the audit correspond to the intended cited works.",
    "clinical-deidentify": "Direct identifier keys and common email or phone patterns capture only a subset of re-identification risk.",
    "clinical-report-audit": "Required sections can be detected from explicit reporting-standard terminology in the supplied text.",
    "cohort-summary": "Continuous and categorical variable roles are declared correctly and records represent the intended cohort denominator.",
    "crispr-design": "The supplied sequence is unambiguous DNA and SpCas9 NGG context is the intended nuclease rule.",
    "data-profile": "Rows are comparable observations and each column has a consistent scientific meaning.",
    "differential-expression": "Groups are independent, features are approximately suitable for Welch testing, and samples are biological replicates.",
    "dilution-plan": "Each transfer is made from the immediately preceding well with complete mixing and conserved volume.",
    "dose-response": "Concentrations are positive, ordered on a log scale, and empirical half-range interpolation is scientifically adequate.",
    "enrichment-analysis": "The query is contained in the explicit background and gene-set membership is appropriate for the organism and identifier namespace.",
    "enzyme-kinetics": "Initial-rate observations follow the selected steady-state kinetic model and substrate concentrations are accurate.",
    "expression-qc": "Matrix values are comparable non-negative expression measurements with correctly oriented genes and samples.",
    "figure-specification": "Each panel is intended to support one declared claim from one identifiable data source.",
    "flow-cytometry-summary": "Compensation and transformation are complete and sequential rectangular gates are scientifically appropriate.",
    "gene-evidence": "Gene symbol and organism identify the intended Entrez gene and database links are interpreted as associations, not proof.",
    "glycosylation-scan": "Sequence motifs indicate potential contexts but do not establish site occupancy.",
    "golden-gate-plan": "Fragment sequences and four-base overhang orientations are declared in assembly order.",
    "growth-curve": "Positive measurements contain a log-linear phase that can be approximated by a sliding window.",
    "image-colocalization": "Channels are spatially registered and intensity thresholds are appropriate for the acquisition and background.",
    "image-profile": "Numeric pixels share one intensity scale and image dimensions preserve the intended field of view.",
    "image-segment": "A global threshold and declared connectivity are suitable for the objects being quantified.",
    "immunoassay-quantification": "The selected calibration range is linear and dilution factors represent the original sample concentration.",
    "literature-evidence": "The bounded database query adequately represents the intended research concept.",
    "manuscript-audit": "Section labels, claims, and availability declarations accurately represent the submitted manuscript package.",
    "ncbi-fetch": "Identifiers, database, return type, and return mode are compatible with the requested Entrez records.",
    "ncbi-info": "The live Entrez metadata response represents current database and field availability.",
    "ncbi-link": "Entrez link sets express database relationships and may not imply direct biological evidence.",
    "ncbi-search": "The Entrez query syntax, database, pagination, and sort choice represent the intended search.",
    "ncbi-search-summary": "Search identifiers and summary records are retrieved from the same bounded Entrez query context.",
    "ncbi-summary": "The supplied identifiers belong to the declared Entrez database and summary schema version.",
    "network-analysis": "Edges represent comparable relationships and duplicate or directional semantics are declared correctly.",
    "patent-disclosure-audit": "The supplied disclosure is a research record rather than a legal opinion or jurisdiction-specific filing analysis.",
    "pcr-plan": "Component volumes are per reaction, concentrations are handled upstream, and pipetting overage is appropriate.",
    "point-tracking": "Frame coordinates share one scale and nearest-neighbor displacement does not exceed the declared bound.",
    "primer-design": "An unambiguous intended template and declared Primer3 thermodynamic settings are adequate for candidate screening before reference-aware specificity review.",
    "qpcr-relative-expression": "Amplification efficiencies are validated, reference assays are stable, and calibrators define the biological baseline.",
    "response-matrix": "Every supplied reviewer comment requires one traceable response and manuscript action.",
    "restriction-plan": "The enzyme motif library and supplied DNA strand are appropriate for sequence-site mapping.",
    "reviewer-assessment": "Claim text, evidence design, replication status, and review-domain flags faithfully represent the manuscript.",
    "sequence-back-translate": "Preferred-codon substitution is sufficient for deterministic screening and is not full expression optimization.",
    "sequence-inspect": "The declared alphabet is correct and non-canonical symbols should be retained as ambiguity rather than guessed.",
    "single-cell-qc": "Genes are rows, cells are columns, counts are non-negative, and thresholds are exploratory rather than universal.",
    "survival-analysis": "Censoring is non-informative and event indicators and durations are correctly aligned.",
    "tumor-mutation-burden": "Callable territory and eligible somatic variant classes match the assay and intended research definition.",
    "variant-evidence": "The query identifies the intended ClinVar records and classifications require assertion-context review.",
    "variant-summary": "Variants use one coordinate and reference system and ref/alt alleles are normalized sufficiently for descriptive counting.",
}


COMPLEMENTS = {
    "gene-evidence": ["literature-evidence", "variant-evidence"],
    "variant-evidence": ["gene-evidence", "literature-evidence"],
    "literature-evidence": ["citation-audit"],
    "primer-design": ["restriction-plan"],
    "golden-gate-plan": ["restriction-plan", "sequence-inspect"],
    "glycosylation-scan": ["sequence-inspect"],
    "differential-expression": ["expression-qc", "enrichment-analysis"],
    "enrichment-analysis": ["differential-expression", "network-analysis"],
    "single-cell-qc": ["expression-qc"],
    "tumor-mutation-burden": ["variant-summary", "variant-evidence"],
    "image-segment": ["image-profile"],
    "image-colocalization": ["image-profile"],
    "biomarker-performance": ["cohort-summary"],
    "survival-analysis": ["cohort-summary"],
    "manuscript-audit": ["citation-audit", "figure-specification", "reviewer-assessment"],
    "reviewer-assessment": ["manuscript-audit", "response-matrix"],
    "patent-disclosure-audit": ["literature-evidence"],
}
